name: flutter_ecommerce
description: A comprehensive e-commerce application
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  mobx: ^2.2.1
  flutter_mobx: ^2.1.1
  get_it: ^7.6.4
  dio: ^5.3.3
  json_annotation: ^4.8.1
  shared_preferences: ^2.2.2
  flutter_stripe: ^9.5.0+1
  responsive_framework: ^1.1.1
  go_router: ^12.1.1
  cached_network_image: ^3.3.0
  google_sign_in: ^6.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.6
  mobx_codegen: ^2.4.0
  json_serializable: ^6.7.1
  flutter_lints: ^2.0.0